table Vendas
	lineageTag: a956ce06-9a24-4227-90e4-22bd303f6819

	column ID-Produto
		dataType: string
		lineageTag: ce820cba-4d39-47ae-9dff-069c7c513b40
		summarizeBy: none
		sourceColumn: ID-Produto

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: 0cfcb3a0-8f03-476f-bd17-3b73d0024111
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 3da893ea-7b74-428b-8eba-aa7acfb0f035
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: f89903c4-2cb3-4c53-876b-a496ae83becf
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Fabricantes
		dataType: string
		lineageTag: a509588c-5526-4639-8148-95ae3fb25c0f
		summarizeBy: none
		sourceColumn: Fabricantes

		annotation SummarizationSetBy = Automatic

	column Loja
		dataType: string
		lineageTag: e2b5c1ed-c4cb-436f-a9a9-5e9b8dc29c70
		summarizeBy: none
		sourceColumn: Loja

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: cab20b74-2be2-4a65-9e63-8c13c129479b
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 8233f47d-7584-4746-a68f-f6601408947f
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: fb271ab6-863c-4ac0-931b-0c7d317130b4
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column ID-Vendedor
		dataType: int64
		formatString: 0
		lineageTag: bfdb033a-15eb-49eb-aec5-2fa00da239c3
		summarizeBy: sum
		sourceColumn: ID-Vendedor

		annotation SummarizationSetBy = Automatic

	column 'Comissão (Percentual)'
		dataType: int64
		formatString: 0
		lineageTag: 505c1b02-a992-4cf7-9775-a6766a6278c0
		summarizeBy: sum
		sourceColumn: Comissão (Percentual)

		annotation SummarizationSetBy = Automatic

	column 'Data Venda'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 33c71f4d-3d64-4e99-89ef-55713abc6cfb
		summarizeBy: none
		sourceColumn: Data Venda

		variation Variation
			isDefault
			relationship: 1696ee2a-039c-4ad5-aff1-426ffff823b0
			defaultHierarchy: LocalDateTable_18904fc5-35c3-4936-bbe6-7f2f6bd6a1ec.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ValorVenda
		dataType: double
		lineageTag: d7d24d0a-ffba-4c69-83c5-3ac4d0bc5f52
		summarizeBy: sum
		sourceColumn: ValorVenda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Custo
		dataType: int64
		formatString: 0
		lineageTag: 625b7daa-7816-41ec-8cf6-de0799262501
		summarizeBy: sum
		sourceColumn: Custo

		annotation SummarizationSetBy = Automatic

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\LEAO\OneDrive\Documentos\DSA - Data Science Academy\Cap05\Dados_Comerciais\Dados_Comerciais.xlsx"), null, true),
				    Vendas_Sheet = Fonte{[Item="Vendas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Vendas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID-Produto", type text}, {"Produto", type text}, {"Categoria", type text}, {"Segmento", type text}, {"Fabricante", type text}, {"Loja", type text}, {"Cidade", type text}, {"Estado", type text}, {"Vendedor", type text}, {"ID-Vendedor", Int64.Type}, {"Comissão (Percentual)", Int64.Type}, {"Data Venda", type date}, {"ValorVenda", type number}, {"Custo", Int64.Type}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Fabricante", "Fabricantes"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_ResultType = Table

